[package]
name = "stackdriver_logger"
version = "0.3.0"
description = "A logger for Google's Stackdriver with a cli-friendly fallback for local development"
authors = ["Kamek <b.kamek@gmail.com>"]
license = "MIT/Apache-2.0"
categories = ["development-tools::debugging"]
keywords = ["log", "logging", "cloud", "google", "stackdriver"]
readme = "README.md"
repository = "https://github.com/kamek-pf/stackdriver-logger/"

[dependencies]
log = "0.4.1"
serde_json = "1.0.19"
chrono = "0.4.2"
pretty_env_logger = "0.2.3"
